[project]
name = "screening"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.14"
dependencies = [
    "accelerate>=1.7.0",
    "electrolyte_fm",
    "lightning>=2.5.1",
    "pandas>=2.2.3",
    "rdkit>=2024.9.6",
    "torch>=2.6.0",
    "typer>=0.15.2",
]

[tool.uv.sources]
electrolyte_fm = { path = "../../", editable = true }

[dependency-groups]
dev = [
    "pytest~=8.0",
]

[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = [".", "test"]
addopts = "--color yes"
