#!/bin/bash
# Source this to activate the environment

# Locate Project Root
GIT_ROOT=$(git rev-parse --show-toplevel)

# Activate virtual environment
source .venv/bin/activate

# Add NVIDIA libraries
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${GIT_ROOT}/.venv/lib64):${GIT_ROOT}.venv/lib)"

# DISABLE Compat Check
export DS_SKIP_CUDA_CHECK=1

# HuggingFace
export HF_HOME="$GIT_ROOT/.cache/huggingface"

# Julia
export JULIA_CONDAPKG_BACKEND=Null
export JULIA_PYTHONCALL_EXE="${GIT_ROOT}/.venv/bin/python)"
