#!/bin/bash
# Source this to activate the environment

# Activate virtual environment
source .venv/bin/activate

# Add NVIDIA libraries
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${GIT_ROOT}/.venv/lib64:${GIT_ROOT}.venv/lib"

# DISABLE Compat Check
export DS_SKIP_CUDA_CHECK=1

# Julia
export JULIA_CONDAPKG_BACKEND=Null
export JULIA_PYTHONCALL_EXE="${GIT_ROOT}/.venv/bin/python"
