#!/bin/bash
# Source this to activate the environment
PROJECT_DIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

# Activate virtual environment
source .venv/bin/activate

# Add NVIDIA libraries
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:$PROJECT_DIR/.venv/lib64:$PROJECT_DIR/.venv/lib"

# DISABLE Compat Check
export DS_SKIP_CUDA_CHECK=1

# Julia
export JULIA_CONDAPKG_BACKEND=Null
export JULIA_PYTHONCALL_EXE="$PROJECT_DIR/.venv/bin/python"
