[tool.poetry]
name = "electrolyte-fm"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
torch = {version = "~2.3"}
torchmetrics = "^1.4.0"
lightning = "~2.3"
jsonargparse = {extras = ["signatures", "jsonnet"], version = "^4.27"}
transformers = "^4.40"
deepspeed = { git = "https://github.com/microsoft/DeepSpeed.git", rev = "5f631abc2f930ecece38fae05dc9bd3923c555dd"}
wandb = "^0.16"
typer = "^0.9"
datasets = "^2.20"
pyspark = "^3.5.0"
rich = "^13"
pydoe2 = "^1.3"
jsonnet = "^0.20.0"
scikit-learn= "^1.5.1"
selfies= "^2.1.0"
rdkit = "^2024.3.5"
smirk = {git = "git@github.com:BattModels/smirk.git", rev = "8061286a219420571d606d98083dd900aaa21d02" }

# Dependencies to support additional tokenizers
smilespe = { version = "==0.0.3", optional = true }
gensim = {version = "^4.3.3", optional = true } # Needed to avoid 4.3.2 (https://github.com/piskvorky/gensim/issues/3541)
apetokenizer = { git = "https://github.com/mikemayuare/apetokenizer.git", rev = "8b070d6278503bcf8ad2eedc1756ac34f4bbd981", optional = true }

[tool.poetry.extras]
tokenizers = ["rdkit", "smilespe", "gensim", "apetokenizer"]

[tool.poetry.group.dev.dependencies]
pytest = "^8"
pre-commit = "^3.7"
ruff = "^0.5.4"

[tool.poetry.group.plotting.dependencies]
# Optional Dependency for plotting
matplotlib = "~3.9"

[tool.poetry.group.tokenizers.dependencies]
# Optional Dependencies for third-party tokenizers
smilespe = "0.0.3"

[tool.poetry.group.plotting.dependencies]
# Optional Dependency for plotting
matplotlib = "~3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = [".", "test"]
addopts = "--color yes"

[tool.ruff.lint]
ignore = ["F401"]

[tool.ruff.lint.extend-per-file-ignores]
"test_*.py" = ["F811"]
