[project]
name = "electrolyte-fm"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "torch~=2.6",
    "torchmetrics~=1.7",
    "lightning~=2.5",
    "jsonargparse[signatures,jsonnet]>=4.27",
    "transformers>=4.40",
    "deepspeed @ git+https://github.com/microsoft/DeepSpeed.git@v0.16.4",
    "wandb>=0.16",
    "typer>=0.9",
    "datasets>=2.20",
    "rich>=13",
    "pydoe2>=1.3",
    "jsonnet>=0.21.0",
    "scikit-learn>=1.5.1",
    "selfies>=2.1.0",
    "rdkit>=2024.3.5",
    "smirk",
    "safetensors>=0.5.1",
    "pytorch-lightning~=2.5",
    "pandas>=2.2.3",
    "numpy>=2.2.4",
]

[optional-dependencies]
tokenizers = [
    "rdkit",
    "smilespe==0.0.3",
    "gensim>=4.3.3",
    "apetokenizer @ git+https://github.com/mikemayuare/apetokenizer.git@8b070d6278503bcf8ad2eedc1756ac34f4bbd981",
    "pyspark>=3.5.0",
]

[dependency-groups]
dev = [
    "pytest>=8",
    "pre-commit>=3.7",
    "ruff>=0.5.4",
    "huggingface-hub>=0.35.3",
]
plotting = [
    "matplotlib~=3.9",
]
tokenizers = [
    "smilespe==0.0.3",
]

[tool.setuptools]
packages = ["electrolyte_fm"]

[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = [".", "test"]
addopts = "--color yes"

[tool.pytest.ini_options.markers]
gpu = "tests that require a GPU to run"

[tool.ruff.lint]
ignore = ["F401"]

[tool.ruff.lint.extend-per-file-ignores]
"test_*.py" = ["F811"]
"**/__init__.py" = ["F401"]


[tool.uv.sources]
smirk = { git = "https://github.com/BattModels/smirk", rev = "main" }
