[project]
name = "electrolyte-fm"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "torch~=2.6",
    "torchmetrics~=1.7",
    "lightning~=2.5",
    "jsonargparse[signatures,jsonnet]>=4.27",
    "transformers>=4.40",
    "deepspeed @ git+https://github.com/microsoft/DeepSpeed.git@v0.16.4",
    "wandb>=0.16",
    "typer>=0.9",
    "datasets>=2.20",
    "rich>=13",
    "pydoe2>=1.3",
    "jsonnet>=0.20.0",
    "scikit-learn>=1.5.1",
    "selfies>=2.1.0",
    "rdkit>=2024.3.5",
    "smirk @ git+ssh://git@github.com/BattModels/smirk.git@dfdd9dc27c066f956b69d1f55c2d4717beb7838d",
    "safetensors>=0.5.1",
    "pytorch-lightning~=2.5"
]

[optional-dependencies]
tokenizers = [
    "rdkit",
    "smilespe==0.0.3",
    "gensim>=4.3.3",
    "apetokenizer @ git+https://github.com/mikemayuare/apetokenizer.git@8b070d6278503bcf8ad2eedc1756ac34f4bbd981",
    "pyspark>=3.5.0",
]

[dependency-groups]
dev = [
    "pytest>=8",
    "pre-commit>=3.7",
    "ruff>=0.5.4",
]
plotting = [
    "matplotlib~=3.9",
]
tokenizers = [
    "smilespe==0.0.3",
]

[tool.setuptools]
packages = ["electrolyte_fm"]

[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = [".", "test"]
addopts = "--color yes"

[tool.ruff.lint.extend-per-file-ignores]
"**/__init__.py" = ["F401"]
