#!/usr/bin/env python
import json
from pathlib import Path

import typer

from submit import render

cli = typer.Typer(rich_markup_mode="markdown")


@cli.command()
def resubmit(
    template: str = typer.Argument(
        file_okay=True, dir_okay=False, help="Jinja2 Template to render"
    ),
    ckpt=typer.Argument(file_okay=False, dir_okay=True, help="Checkpoint to Resume"),
    resume_wandb: bool = typer.Option(False, help="Resume wandb run"),
):
    ckpt = Path(ckpt)
    assert ckpt.is_dir(), f"Checkpoint path {ckpt} is not a directory"
    config = Path(ckpt).parent.parent.joinpath("job_config.json")
    assert config.is_file(), f"Job Config file was not found at {config}"
    with open(config, "r") as fid:
        job_config = json.load(fid)

    job_config["train"]["ckpt_path"] = str(ckpt.resolve())
    if resume_wandb:
        job_config["env"]["WANBD_RESUME"] = "must"
        job_config["env"]["WANDB_ID"] = str(ckpt.parent.parent.name)

    script = render(template, job_config)
    print(script)


if __name__ == "__main__":
    cli()
