#!/usr/bin/env -S uv run python
"""
Build a HuggingFace dataset from one or more ASE LMDB (".aselmdb") files.

- Input: a directory containing ``*.aselmdb`` files (single split) OR a
  directory with subdirectories, each containing ``*.aselmdb`` (multi-split),
  or a directory containing ``*.tar.gz``/``*.tgz`` archives where each archive
  represents a split and contains ``*.aselmdb`` inside. You may also pass a
  single ``.aselmdb`` or ``.tar.gz`` file.
- Processing: entries are read, normalized with RDKit (bonding, identifiers),
  and curated fields are produced.
- Output: an Arrow dataset written via ``datasets`` (``save_to_disk``).
- Multiprocessing: heavy per-record processing runs with ``map(num_proc=...)``.

Outputs per record:
- unique_id, composition, SMILES, InChI, InChIKey
- total-energy, homo, lumo, gap, nl_energy, charge, spin
- atomic-numbers, atomic-coordinates (flattened), atomic-isotope (or None)
- bond-connections (u,v pairs flattened) and bond-orders
- mulliken_charges, lowdin_charges, nbo_charges (if present)

Bonding and identifiers are computed with RDKit from geometry, using a
sanitization pipeline modeled on opt/tmQM/build.py.
"""

import argparse
import json
import os
from pathlib import Path
import tarfile
import tempfile
import threading
from queue import Queue
import zlib
from collections.abc import Generator
from typing import Any

import lmdb
import numpy as np
from rdkit import Chem
from rdkit.Chem import inchi as rd_inchi
import rdkit.Chem.AllChem as AllChem  # noqa: F401
from rdkit.Chem import rdDetermineBonds, rdmolfiles, rdmolops
from rdkit.Chem import rdMolDescriptors
import logging
from datasets import Dataset, DatasetDict


def iter_aselmdb(path: str) -> Generator[dict[str, Any], None, None]:
    env = lmdb.open(path, readonly=True, lock=False, max_readers=2048, subdir=False)
    with env.begin() as txn:
        cur = txn.cursor()
        for _, v in cur:
            try:
                j = json.loads(zlib.decompress(v))
                if isinstance(j, dict):
                    yield j
            except Exception:
                logging.debug("Failed to decode LMDB value as JSON", exc_info=True)
                continue


def _ndarray_from_json(obj: Any) -> np.ndarray | None:
    if isinstance(obj, dict) and "__ndarray__" in obj:
        arr = obj["__ndarray__"]
        if not isinstance(arr, list) or len(arr) < 3:
            return None
        shape, dtype, data = arr[0], arr[1], arr[2]
        try:
            a = np.array(data, dtype=dtype)
            if isinstance(shape, list):
                a = a.reshape(shape)
            return a
        except Exception:
            logging.debug("Failed to parse __ndarray__ payload", exc_info=True)
            return None
    return None


def _get(entry: dict[str, Any], key: str) -> Any:
    if key in entry:
        return entry[key]
    d = entry.get("data")
    if isinstance(d, dict) and key in d:
        return d[key]
    return None


def _as_float(val: Any) -> float | None:
    if val is None:
        return None
    if isinstance(val, int | float):
        return float(val)
    a = _ndarray_from_json(val)
    if a is not None:
        try:
            return float(np.ravel(a)[0])
        except Exception:
            return None
    try:
        return float(val)
    except Exception:
        return None


def _as_list_float(val: Any) -> list[float] | None:
    if val is None:
        return None
    if isinstance(val, list):
        return [float(x) for x in val]
    a = _ndarray_from_json(val)
    if a is not None:
        return [float(x) for x in np.ravel(a).tolist()]
    return None


def build_rdkit_mol(
    numbers: list[int], positions: np.ndarray, charge: int = 0
) -> Chem.Mol | None:
    # Build XYZ block
    pt = Chem.GetPeriodicTable()
    lines = [str(len(numbers)), "generated by aselmdb_to_jsonl"]
    for z, (x, y, zc) in zip(numbers, positions):
        sym = pt.GetElementSymbol(int(z))
        lines.append(f"{sym} {x:.8f} {y:.8f} {zc:.8f}")
    xyz = "\n".join(lines)

    def _attempt(use_hueckel: bool) -> Chem.Mol:
        m = Chem.MolFromXYZBlock(xyz)
        if m is None:
            raise ValueError("MolFromXYZBlock returned None")
        rdDetermineBonds.DetermineBonds(m, charge=int(charge), useHueckel=use_hueckel)
        # Sanitize following opt/tmQM/build.py
        rdmolops.AssignStereochemistryFrom3D(m)
        m = rdmolops.HapticBondsToDative(m)
        rdmolops.SanitizeMol(m, catchErrors=True)
        m = rdmolops.RemoveHs(m, sanitize=False)
        smi_tmp = Chem.MolToSmiles(m)
        m = Chem.MolFromSmiles(smi_tmp, sanitize=False)
        rdmolops.SanitizeMol(m, catchErrors=True)
        if m is None:
            raise ValueError("Failed to round-trip molecule through SMILES")
        return m

    # Try Hückel method first, then fallback to default
    try:
        logging.debug("DetermineBonds(useHueckel=True), charge=%s", charge)
        mol = _attempt(True)
        logging.info("Bonding determined using Hückel method")
        return mol
    except Exception:
        logging.warning(
            "Hückel bond perception failed; trying default method", exc_info=True
        )
        try:
            logging.debug("DetermineBonds(useHueckel=False), charge=%s", charge)
            mol = _attempt(False)
            logging.info("Bonding determined using default method")
            return mol
        except Exception:
            logging.error(
                "Bond perception failed with both Hückel and default methods",
                exc_info=True,
            )
            raise ValueError("failed to determine bonds with RDKit")


def smiles_inchi_from_mol(mol: Chem.Mol) -> tuple[str, str, str]:
    p = rdmolfiles.SmilesWriteParams()
    # p.isomericSmiles = True
    p.canonical = True
    p.allHsExplicit = False
    p.allBondsExplicit = False
    p.doKekule = False
    p.includeDativeBonds = False
    smi = Chem.MolToSmiles(mol, p)

    # Validate and sanitize strictly
    m2 = Chem.MolFromSmiles(smi)
    if m2 is None:
        raise ValueError("invalid SMILES from mol")
    Chem.SanitizeMol(m2)

    inchi = rd_inchi.MolToInchi(m2)
    inchikey = rd_inchi.MolToInchiKey(m2)
    return smi, inchi, inchikey


def record_from_entry(entry: dict[str, Any]) -> dict[str, Any] | None:
    # Extract base fields
    uid = entry.get("unique_id")
    composition = _get(entry, "composition")
    energy = _as_float(_get(entry, "energy"))
    homo = _as_float(_get(entry, "homo_energy"))
    lumo = _as_float(_get(entry, "lumo_energy"))
    gap = _as_float(_get(entry, "homo_lumo_gap"))
    nl_energy = _as_float(_get(entry, "nl_energy"))
    charge = int(_get(entry, "charge") or 0)
    spin = int(_get(entry, "spin") or 0)

    if homo is not None and lumo is None and gap is not None:
        lumo = homo + gap
    if gap is None and homo is not None and lumo is not None:
        gap = lumo - homo

    nums_any = _get(entry, "numbers")
    pos_any = _get(entry, "positions")
    numbers = _as_list_float(nums_any)
    numbers = [int(round(x)) for x in numbers] if numbers is not None else None
    pos = _ndarray_from_json(pos_any)
    if pos is None:
        # Some datasets store as nested lists
        if isinstance(pos_any, list) and pos_any and isinstance(pos_any[0], list):
            pos = np.array(pos_any, dtype=float)
    if numbers is None or pos is None:
        raise ValueError("missing atomic numbers or positions in entry")

    # Build RDKit mol (sanitized) and extract bonds + identifiers
    mol = build_rdkit_mol(numbers, pos, charge=charge)

    # Geometry from sanitized mol (without Hs)
    conf = mol.GetConformer() if mol.GetNumConformers() else None
    if conf is None:
        # If no conformer retained (unlikely), fallback to original
        atom_numbers = [int(z) for z in numbers]
        coords_flat = [float(x) for x in np.ravel(pos).tolist()]
        isotopes = [None for _ in atom_numbers]
    else:
        atom_numbers = [int(a.GetAtomicNum()) for a in mol.GetAtoms()]
        isotopes = [
            int(a.GetIsotope()) if a.GetIsotope() != 0 else None for a in mol.GetAtoms()
        ]
        coords_flat = []
        for i in range(mol.GetNumAtoms()):
            p = conf.GetAtomPosition(i)
            coords_flat.extend([float(p.x), float(p.y), float(p.z)])

    # Bonds
    bond_conns: list[int] = []
    bond_orders: list[int] = []
    bt_map = {
        Chem.BondType.SINGLE: 1,
        Chem.BondType.DOUBLE: 2,
        Chem.BondType.TRIPLE: 3,
        Chem.BondType.AROMATIC: 1,
        Chem.BondType.DATIVE: 1,
    }
    for b in mol.GetBonds():
        bond_conns.extend([int(b.GetBeginAtomIdx()), int(b.GetEndAtomIdx())])
        bond_orders.append(int(bt_map.get(b.GetBondType(), 1)))

    # Identifiers
    try:
        smiles, inchi, inchikey = smiles_inchi_from_mol(mol)
    except Exception:
        logging.warning("Failed to compute SMILES/InChI identifiers", exc_info=True)
        smiles = inchi = inchikey = None
    # If SMILES is not available, skip this entry
    if not smiles:
        logging.warning("Skipping entry due to missing SMILES encoding")
        return None

    # Validate SMILES consistency against original geometry (no new heavy atoms)
    try:
        m2 = Chem.MolFromSmiles(smiles)
        if m2 is None:
            raise ValueError("MolFromSmiles returned None for generated SMILES")
        Chem.SanitizeMol(m2)
        from collections import Counter

        orig_heavy = [int(z) for z in numbers if int(z) != 1]
        smi_heavy = [a.GetAtomicNum() for a in m2.GetAtoms() if a.GetAtomicNum() != 1]
        if Counter(orig_heavy) != Counter(smi_heavy):
            logging.warning(
                "Skipping entry due to heavy-atom composition mismatch: orig=%s, smiles=%s",
                Counter(orig_heavy),
                Counter(smi_heavy),
            )
            return None
        # Optional: check total formal charge
        try:
            smiles_charge = rdmolops.GetFormalCharge(m2)
            if smiles_charge != charge:
                logging.warning(
                    "Skipping entry due to formal charge mismatch: dataset=%s, smiles=%s",
                    charge,
                    smiles_charge,
                )
                return None
        except Exception:
            logging.debug("Could not compute formal charge from SMILES", exc_info=True)
    except Exception:
        logging.warning(
            "Skipping entry due to SMILES validation failure", exc_info=True
        )
        return None

    # Compute composition if missing
    if not composition:
        try:
            composition = rdMolDescriptors.CalcMolFormula(mol)
        except Exception:
            logging.debug(
                "Failed to compute molecular formula from RDKit mol", exc_info=True
            )

    # Charges per atom
    mulliken = _as_list_float(_get(entry, "mulliken_charges"))
    lowdin = _as_list_float(_get(entry, "lowdin_charges"))
    nbo = _as_list_float(_get(entry, "nbo_charges"))

    rec = {
        "unique_id": uid,
        "composition": composition,
        "SMILES": smiles,
        "InChI": inchi,
        "InChIKey": inchikey,
        "total-energy": energy,
        "homo": homo,
        "lumo": lumo,
        "gap": gap,
        "charge": charge,
        "spin": spin,
        "nl_energy": nl_energy,
        "atomic-numbers": atom_numbers,
        "atomic-coordinates": coords_flat,
        "atomic-isotope": isotopes,
        "bond-connections": bond_conns,
        "bond-orders": bond_orders,
        "mulliken_charges": mulliken,
        "lowdin_charges": lowdin,
        "nbo_charges": nbo,
    }
    return rec


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Build Arrow dataset from ASE LMDB (.aselmdb) files using datasets"
    )
    ap.add_argument(
        "input",
        help=(
            "Path to a .aselmdb file, a folder of *.aselmdb (single split), or a folder"
            " of subfolders each containing *.aselmdb (multi-split)"
        ),
    )
    ap.add_argument(
        "--output",
        "-o",
        required=True,
        help="Output dataset directory (will be created, contains Arrow files)",
    )
    ap.add_argument(
        "--num-proc",
        type=int,
        default=os.cpu_count() or 1,
        help="Number of processes for per-record processing (datasets.map)",
    )
    ap.add_argument(
        "--read-workers",
        type=int,
        default=4,
        help="Number of threads to stream LMDB entries from files/archives",
    )
    ap.add_argument(
        "--max-shard-size",
        default="1GB",
        help="Maximum shard size passed to save_to_disk (e.g., 1GB, 500MB)",
    )
    ap.add_argument(
        "--log-level",
        default="INFO",
        choices=["CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG"],
        help="Logging level (default: INFO)",
    )
    args = ap.parse_args(argv)

    inp = Path(args.input)
    out_dir = Path(args.output)

    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s %(levelname)s %(message)s",
    )

    # Discover splits
    splits = _discover_splits(inp)
    if not splits:
        raise SystemExit(f"No .aselmdb files found under: {inp}")

    logging.info("Discovered splits: %s", {k: len(v) for k, v in splits.items()})

    # Build dataset(s)
    datasets = {}
    for split, sources in splits.items():
        logging.info("Building split '%s' from %d source(s)", split, len(sources))
        ds = _build_split_dataset(sources, num_proc=args.num_proc, read_workers=args.read_workers)
        datasets[split] = ds

    # Save to disk (always as DatasetDict for predictable structure)
    logging.info("Saving DatasetDict with %d split(s) to %s", len(datasets), out_dir)
    ds_dict = DatasetDict(datasets)
    ds_dict.save_to_disk(out_dir, max_shard_size=args.max_shard_size)

    logging.info("Done. Saved dataset(s) to %s", out_dir)
    print(f"Saved dataset(s) to {out_dir}")
    return 0


# ------------------------
# Dataset building helpers
# ------------------------


def _discover_splits(root: Path) -> dict[str, list[tuple[str, ...]]]:
    """Find input .aselmdb files and group them into splits.

    Rules:
    - If ``root`` is a file ending with .aselmdb -> one split named by stem.
    - If ``root`` is a .tar.gz/.tgz -> one split named by archive basename; all
      .aselmdb members are included.
    - If ``root`` is a directory with ``*.aselmdb`` -> one split named after the
      directory (e.g., 'neural_val').
    - If ``root`` contains subdirectories, each subdirectory with ``*.aselmdb``
      becomes a split named by the subdirectory.
    - If ``root`` contains ``*.tar.gz``/``*.tgz`` archives, each archive becomes
      a split named by its basename (without the archive suffix).
    """
    if root.is_file() and root.suffix == ".aselmdb":
        return {root.stem: [("file", str(root))]}
    if root.is_file() and (str(root).endswith(".tar.gz") or str(root).endswith(".tgz")):
        split = _basename_without_targz(root.name)
        members = _list_aselmdb_in_tar(str(root))
        return {split: [("tar", str(root), m) for m in members]}

    if root.is_dir():
        # Case 1: directory has *.aselmdb directly
        files_here = sorted(str(p) for p in root.glob("*.aselmdb"))
        if files_here:
            return {root.name: [("file", f) for f in files_here]}

        # Case 2: subdirectories are splits
        splits: dict[str, list[tuple[str, ...]]] = {}
        for sub in sorted([p for p in root.iterdir() if p.is_dir()]):
            files = sorted(str(p) for p in sub.glob("*.aselmdb"))
            if files:
                splits[sub.name] = [("file", f) for f in files]
        # Tarball splits at root
        for tb in sorted(
            [
                p
                for p in root.iterdir()
                if p.is_file() and (str(p).endswith(".tar.gz") or str(p).endswith(".tgz"))
            ]
        ):
            split = _basename_without_targz(tb.name)
            members = _list_aselmdb_in_tar(str(tb))
            if members:
                splits[split] = [("tar", str(tb), m) for m in members]
        return splits

    return {}

def _basename_without_targz(name: str) -> str:
    for suf in (".tar.gz", ".tgz"):
        if name.endswith(suf):
            return name[: -len(suf)]
    # fallback
    return Path(name).stem


def _list_aselmdb_in_tar(tar_path: str) -> list[str]:
    with tarfile.open(tar_path, "r:gz") as tf:
        return [m.name for m in tf.getmembers() if m.isfile() and m.name.endswith(".aselmdb")]


def _iter_aselmdb_from_tar(tar_path: str, member_name: str):
    """Iterate entries from a single .aselmdb member inside a tar.gz archive.

    Streams the member to a temporary file without extracting the entire archive,
    then uses the existing LMDB reader to iterate entries.
    """
    with tarfile.open(tar_path, "r:gz") as tf:
        try:
            m = tf.getmember(member_name)
        except KeyError:
            logging.warning("Missing member %s in %s", member_name, tar_path)
            return
        fobj = tf.extractfile(m)
        if fobj is None:
            logging.warning("Could not open member %s from %s", member_name, tar_path)
            return
        with tempfile.NamedTemporaryFile(suffix=".aselmdb", delete=False) as tmp:
            tmp_path = tmp.name
            while True:
                chunk = fobj.read(1024 * 1024)
                if not chunk:
                    break
                tmp.write(chunk)
    try:
        for entry in iter_aselmdb(tmp_path):
            yield entry
    finally:
        try:
            os.remove(tmp_path)
        except Exception:
            logging.debug("Failed to remove temp file %s", tmp_path, exc_info=True)


def _entries_from_sources(sources: list[tuple[str, ...]], read_workers: int):
    """Concurrent producer that streams entries from file and tar sources."""
    q: "Queue[object]" = Queue(maxsize=2048)
    sentinel = object()
    src_iter = iter(sources)
    lock = threading.Lock()
    finished = 0
    n_workers = max(1, int(read_workers))

    def next_src():
        nonlocal src_iter
        with lock:
            try:
                return next(src_iter)
            except StopIteration:
                return None

    def worker():
        nonlocal finished
        while True:
            src = next_src()
            if src is None:
                break
            try:
                if src[0] == "file":
                    _, path = src
                    it = iter_aselmdb(path)
                elif src[0] == "tar":
                    _, tar_path, member = src
                    it = _iter_aselmdb_from_tar(tar_path, member)
                else:
                    it = iter(())
                for entry in it:
                    q.put({"raw": json.dumps(entry)}, block=True)
            except Exception:
                logging.exception("Reader failed for source: %s", src)
        with lock:
            finished += 1
            if finished == n_workers:
                q.put(sentinel)

    threads = [threading.Thread(target=worker, daemon=True) for _ in range(n_workers)]
    for t in threads:
        t.start()

    while True:
        item = q.get()
        if item is sentinel:
            break
        yield item


OUTPUT_COLUMNS = [
    "unique_id",
    "composition",
    "SMILES",
    "InChI",
    "InChIKey",
    "total-energy",
    "homo",
    "lumo",
    "gap",
    "charge",
    "spin",
    "nl_energy",
    "atomic-numbers",
    "atomic-coordinates",
    "atomic-isotope",
    "bond-connections",
    "bond-orders",
    "mulliken_charges",
    "lowdin_charges",
    "nbo_charges",
]


def _process_batch(batch: dict) -> dict:
    raws: list[str] = batch["raw"]
    out: dict[str, list] = {k: [] for k in OUTPUT_COLUMNS}
    keep: list[bool] = []
    for s in raws:
        try:
            rec = record_from_entry(json.loads(s))
        except Exception:
            rec = None
        if rec is None:
            # Fill placeholders; we'll filter later
            for k in OUTPUT_COLUMNS:
                # Scalars -> None, lists -> empty list
                if k in {
                    "atomic-numbers",
                    "atomic-coordinates",
                    "atomic-isotope",
                    "bond-connections",
                    "bond-orders",
                    "mulliken_charges",
                    "lowdin_charges",
                    "nbo_charges",
                }:
                    out[k].append([])
                else:
                    out[k].append(None)
            keep.append(False)
        else:
            for k in OUTPUT_COLUMNS:
                out[k].append(rec.get(k))
            keep.append(True)

    out["__keep__"] = keep
    return out


def _build_split_dataset(sources: list[tuple[str, ...]], num_proc: int, read_workers: int) -> Dataset:
    # Stage 1: build a lightweight dataset of raw JSON strings
    ds = Dataset.from_generator(
        _entries_from_sources,
        gen_kwargs={"sources": sources, "read_workers": read_workers},
        keep_in_memory=False,
    )

    # Stage 2: heavy processing in parallel
    ds = ds.map(
        _process_batch,
        batched=True,
        remove_columns=["raw"],
        num_proc=max(1, int(num_proc)),
        desc="Processing records with RDKit",
    )

    # Stage 3: drop failed rows
    ds = ds.filter(lambda keep: keep, input_columns=["__keep__"]).remove_columns(
        ["__keep__"]
    )
    return ds


if __name__ == "__main__":
    raise SystemExit(main())
