"""
QM9: Generate quantum-chemical properties for a SMILES string using RDKit → MOPAC → Gaussian 09

Workflow (Ramakrishnan et al., Sci. Data 1:140022, 2014) with RDKit for initial geometry:
  1) RDKit ETKDG → initial XYZ
  2) MOPAC (PM7) → geometry relaxation
  3) Gaussian 09 B3LYP/6-31G(2df,p) opt + freq, resources auto-detected from SLURM
  4) Parse via cclib + compute additional metrics
  5) Emit JSON; optionally archive intermediates with compression auto-detected (default: xz)

"""
import os
import json
import shutil
import tarfile
import tempfile
import subprocess
import logging
import re
import sys
import time
from pathlib import Path
from typing import List, Tuple, Optional

import typer
from typer import FileText, FileTextWrite
from jinja2 import Template
import cclib
from rdkit import Chem
from rdkit.Chem import AllChem
from openbabel import pybel

GAUSSIAN_TEMPLATE = """%mem={{ mem }}
%nprocshared={{ nproc }}

# {{ method }}/{{ basis }} opt freq

{{ title }}

0 1
{%- for atom, x, y, z in geometry %}
{{ atom }}    {{ '%.6f' % x }}    {{ '%.6f' % y }}    {{ '%.6f' % z }}
{%- endfor %}


"""

app = typer.Typer(help="Compute GDB-9 quantum-chem properties for a SMILES string.")

def run_command(cmd: List[str], cwd: Optional[Path] = None) -> None:
    logging.info(f"Running command: {' '.join(cmd)}")
    subprocess.run(cmd, cwd=str(cwd) if cwd else None, check=True)

def get_slurm_resources() -> Tuple[str, int]:
    """Detect SLURM memory and CPU allocations, fallback to defaults."""
    cpus = int(os.getenv('SLURM_CPUS_PER_TASK') or 8)
    if os.getenv('SLURM_MEM_PER_CPU'):
        mem_per_cpu = int(os.getenv('SLURM_MEM_PER_CPU'))
        total_mem_mb = mem_per_cpu * cpus
    else:
        total_mem_mb = int(os.getenv('SLURM_MEM_PER_NODE') or 4096)
    mem_gb = max(1, total_mem_mb // 1024)
    return f"{mem_gb}GB", cpus

def generate_rdkit_xyz(smiles: str, out_xyz: Path) -> None:
    """Generate initial XYZ from SMILES using RDKit ETKDG conformer embedding."""
    mol = Chem.AddHs(Chem.MolFromSmiles(smiles))
    AllChem.EmbedMolecule(mol, AllChem.ETKDG())
    AllChem.UFFOptimizeMolecule(mol)
    conf = mol.GetConformer()
    with out_xyz.open('w') as f:
        f.write(f"{mol.GetNumAtoms()}\n")
        f.write(f"Generated by RDKit ETKDG for SMILES: {smiles}\n")
        for atom in mol.GetAtoms():
            pos = conf.GetAtomPosition(atom.GetIdx())
            f.write(f"{atom.GetSymbol()} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}\n")

def optimize_pm7(initial_xyz: Path, workdir: Path) -> Path:
    """Run MOPAC PM7 geometry optimization; manually create .mop input and return path to .arc file."""
    # Read initial geometry from XYZ file
    lines = initial_xyz.read_text().splitlines()[2:]
    mop_file = workdir / initial_xyz.with_suffix('.mop').name
    with mop_file.open('w') as f:
        f.write("PM7 XYZ PRECISE\n")
        f.write("PM7 geometry optimization\n")
        f.write("0 1\n")  # neutral, singlet
        for line in lines:
            f.write(line + "\n")
    # Run MOPAC
    run_command(["mopac", str(mop_file)])
    # MOPAC generates an .arc file by default
    return mop_file.with_suffix('.out')

def extract_pm7_geometry(mopac_out: Path, pm7_xyz: Path) -> List[Tuple[str, float, float, float]]:
    """Extract optimized geometry from PM7 output using cclib."""
    data = cclib.io.ccread(str(mopac_out))
    coords = data.atomcoords[-1]
    atomnos = data.atomnos
    pt = Chem.GetPeriodicTable()
    geometry = []
    with pm7_xyz.open('w') as f:
        f.write(f"{data.natom}\n")
        f.write(f"Generated by PM7 relaxation from {mopac_out.name}\n")
        for no, (x, y, z) in zip(atomnos, coords):
            sym = pt.GetElementSymbol(int(no))
            geometry.append((sym, float(x), float(y), float(z)))
            f.write(f"{sym} {x:.6f} {y:.6f} {z:.6f}\n")
    return geometry

def render_gaussian_input(
    geometry: List[Tuple[str, float, float, float]],
    out_file: Path,
    mem: str,
    nproc: int,
    method: str = "B3LYP",
    basis: str = "6-31G(2df,p)",
    title: str = "GDB-9 DFT opt+freq"
) -> None:
    """Render Gaussian input file via Jinja2."""
    template = Template(GAUSSIAN_TEMPLATE)
    out_file.write_text(
        template.render(
            mem=mem,
            nproc=nproc,
            method=method,
            basis=basis,
            title=title,
            geometry=geometry,
        )
    )

def run_gaussian(inp: Path, workdir: Path) -> Path:
    """Run Gaussian job; returns path to log file."""
    run_command(["g09", str(inp)])
    return workdir / inp.with_suffix('.log').name

def extract_r2_from_log(logfile: Path) -> float | None:
    """Extract electronic spatial extent (<R**2>) from Gaussian log file."""
    for line in logfile.read_text().splitlines():
        regex = re.compile(r"<R\*\*2>\s*=\s*([0-9\.\-Ee\+]+)")
        if "Electronic spatial extent" in line:
            match = regex.search(line)
            if match:
                return float(match.group(1))
    return None

def parse_gaussian_output(logfile: Path) -> dict:
    """Parse Gaussian output with cclib and compute metrics."""
    data = cclib.io.ccread(str(logfile))
    props: dict = {}
    # props['A'] = float(data.rotcons[0]) missing
    # props['B'] = float(data.rotcons[1]) missing
    # props['C'] = float(data.rotcons[2]) missing
    # props['mu'] = float(data.dipmom[3]) missing
    props['homo'] = float(data.moenergies[0][data.homos[0]])
    props['lumo'] = float(data.moenergies[0][data.homos[0]+1])
    props['gap'] = props['lumo'] - props['homo']
    props['r2'] = extract_r2_from_log(logfile)
    props['zpve'] = float(data.zpve)
    props['u0'] = float(data.scfenergies[-1])
    props['u298'] = float(data.enthalpy)
    props['h298'] = float(data.enthalpy)
    props['g298'] = float(data.freeenergy)
    # props['cv'] = float(data.cp[0])  # missing
    natoms = int(data.natom)
    props['u0_atom'] = props['u0'] / natoms
    props['u298_atom'] = props['u298'] / natoms
    props['h298_atom'] = props['h298'] / natoms
    props['g298_atom'] = props['g298'] / natoms
    return props

def compute_inchi(smiles: str) -> Tuple[str, str]:
    """Compute InChI and InChIKey via RDKit."""
    mol = Chem.MolFromSmiles(smiles)
    return Chem.MolToInchi(mol), Chem.MolToInchiKey(mol)

def archive_intermediates(workdir: Path, archive_path: Path) -> None:
    """Archive the working directory to a compressed tar file, auto-detecting compression."""
    name = archive_path.name.lower()
    if name.endswith('.tar.xz') or name.endswith('.txz'):
        mode = 'w:xz'
    elif name.endswith('.tar.gz') or name.endswith('.tgz'):
        mode = 'w:gz'
    else:
        mode = 'w'
    logging.info(f"Archiving {workdir} -> {archive_path} with mode {mode}")
    with tarfile.open(str(archive_path), mode) as tar:
        tar.add(str(workdir), arcname=workdir.name)

def process_smiles(smiles: str, archive: bool, archive_filename: Path) -> dict:
    workdir = Path(tempfile.mkdtemp(prefix="gdb9_"))
    logging.info(f"Workdir: {workdir}")
    mem_str, nproc = get_slurm_resources()
    start_time = time.perf_counter()
    try:
        initial_xyz = workdir / "initial.xyz"
        generate_rdkit_xyz(smiles, initial_xyz)
        mopac_out = optimize_pm7(initial_xyz, workdir)
        pm7_xyz = workdir / "pm7_relaxed.xyz"
        geometry = extract_pm7_geometry(mopac_out, pm7_xyz)
        g09_inp = workdir / "dft.com"
        render_gaussian_input(geometry, g09_inp, mem=mem_str, nproc=nproc)
        g09_log = run_gaussian(g09_inp, workdir)
        props = parse_gaussian_output(g09_log)
        walltime = time.perf_counter() - start_time
        inchi, inchikey = compute_inchi(smiles)
        result = {
            'smiles': smiles,
            'InChI': inchi,
            'InChIKey': inchikey,
            "walltime": walltime,
            **props,
        }
        if archive:
            archive_intermediates(workdir, archive_filename)
        return result
    finally:
        logging.info(f"Cleaning up {workdir}")
        shutil.rmtree(str(workdir))

@app.command()
def main(
    smiles: str = typer.Argument(help="SMILES input"),
    output_file: FileTextWrite = typer.Option("-", "--output", "-o", help="Where to write the JSON formated results"),
    archive: bool = typer.Option(False, '--archive', '-a', help="Archive intermediates"),
    archive_filename: Path = typer.Option(Path.cwd() / 'archive.tar.xz', '--archive-filename', '-f', help="Archive filename"),
):
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s: %(message)s")
    result = process_smiles(smiles, archive, archive_filename)
    json.dump(result, output_file, indent=2)
    output_file.write("\n")

if __name__ == '__main__':
    app()
