#!/usr/bin/env python
import typer
import wandb
import logging
import shutil
from pathlib import Path

cli = typer.Typer(rich_markup_mode="markdown")

logging.basicConfig(level=logging.INFO)

# Initialize the W&B API
api = wandb.Api()


@cli.command()
def cleanup(
    dir: Path,
    entity="incite-mist",  # Replace with your W&B entity
    trash=".trash",
    project="mist",
):
    trash = Path(dir, trash).expanduser()
    trash.mkdir(exist_ok=True)
    for dir in Path(dir).expanduser().iterdir():
        if not dir.is_dir():
            continue
        if dir.name.startswith("."):
            continue

        run_id = dir.name
        try:
            logging.info("checking %s", run_id)
            api.run(f"{entity}/{project}/{run_id}")

        except wandb.errors.CommError:
            logging.info(f"Moving {run_id} to trash")
            shutil.move(dir, Path(trash, run_id))

        except Exception as e:
            logging.error(f"Error while checking {run_id}: {e}")


if __name__ == "__main__":
    cli()

