#!/usr/bin/env python
import typer
import wandb
import logging
import shutil
from pathlib import Path

cli = typer.Typer(rich_markup_mode="markdown")

logging.basicConfig(level=logging.INFO)

# Initialize the W&B API
api = wandb.Api()


def run_is_tracked(run_id: str, entity: str, projects: list[str]):
    logging.info("checking %s", run_id)
    for project in projects:
        try:
            api.run(f"{entity}/{project}/{run_id}")
            return True

        except wandb.errors.CommError:
            continue

        except Exception as e:
            logging.error(f"Error while checking {run_id}: {e}")

    return False


@cli.command()
def cleanup(
    dir: Path,
    entity="incite-mist",  # Replace with your W&B entity
    trash=".trash",
    projects: list[str] | None = None,
):
    if projects is None:
        projects = [project.name for project in api.projects(entity)]
        logging.info("Checking for runs in projects: %s", ",".join(projects))

    trash = Path(dir, trash).expanduser()
    trash.mkdir(exist_ok=True)
    for dir in Path(dir).expanduser().iterdir():
        if not dir.is_dir():
            continue
        if dir.name.startswith("."):
            continue

        run_id = dir.name
        if not run_is_tracked(dir.name, entity, projects):
            logging.info(f"Moving {run_id} to trash")
            shutil.move(dir, Path(trash, run_id))


if __name__ == "__main__":
    cli()
