#!/usr/bin/env -S uv run python
import sys
import argparse
import json
from rdkit import Chem


def write_xyz(io, data: str):
    data = json.loads(data)
    num_atoms = len(data["atoms"])
    smi = data["smi"]
    io.write(f"{num_atoms}\n{smi}\n")
    for atom in data["atoms"]:
        elem = Chem.Atom(atom["atomic-number"]).GetSymbol()
        pos = atom["position"]
        io.write(f"{elem} {pos[0]:.6f} {pos[1]:.6f} {pos[2]:.6f}\n")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("input", type=argparse.FileType("r"))
    p.add_argument("--output", type=argparse.FileType("w"), default=sys.stdout)
    args = p.parse_args()

    for line in args.input:
        write_xyz(args.output, line)
