#!/bin/bash
# Source this to activate the environment
DIR="$(git rev-parse --show-toplevel)/opt/TokenizerStats"

# Load modules
if command -v module > /dev/null; then
    module purge
    module --ignore_cache load gcc python/3.11.5 openmpi/4.1.6
fi

# Activate virtual environment
source $DIR/.venv/bin/activate

# Configure HF and Tokenizers
export HF_HOME="$(git rev-parse --show-toplevel)/.cache/huggingface"
export TOKENIZERS_PARALLELISM=false

# Configure julia
export JULIA_CPU_TARGET="generic;znver4,clone_all;znver3,clone_all;haswell"
export JULIA_CONDAPKG_BACKEND=Null
export JULIA_PYTHONCALL_EXE="$DIR/.venv/bin/python"

