#!/bin/bash
# Source this to activate the environment
DIR="$(git rev-parse --show-toplevel)/opt/TokenizerStats"

# Activate virtual environment
source $DIR/.venv/bin/activate

export HF_HOME="$(git rev-parse --show-toplevel)/.cache/huggingface"
export JULIA_CONDAPKG_BACKEND=Null
export JULIA_PYTHONCALL_EXE="$DIR/.venv/bin/python"
