[tool.poetry]
package-mode = false
authors = ["Alexius Wadell <awadell@umich.edu>"]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
mendeleev = "^0.16"
electrolyte_fm = {path = "../..", extras = ["tokenizers"], develop = true}
selfies = "^2.1.2"
jsonnet = "^0.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
