[project]
name = "TokenizerStats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    {name = "Alexius Wadell", email = "awadell@umich.edu"},
]
requires-python = ">=3.10, <3.14"
dependencies = [
    "mendeleev >= 0.16",
    "selfies == 2.1.2",
    "jsonnet ~= 0.20.0",
    "electrolyte-fm",
    "smilespe==0.0.3",
    "apetokenizer @ git+https://github.com/mikemayuare/apetokenizer.git@8b070d6278503bcf8ad2eedc1756ac34f4bbd981",
]

[tool.uv.sources]
electrolyte-fm = { path = "../../", editable = true }
