name: bayesian-ci
on:
  push:
    paths:
      - "opt/BayesianScaling/**"
  pull_request:
    paths:
      - "opt/BayesianScaling/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: "release"
    - uses: julia-actions/cache@v1
    - uses: julia-actions/julia-buildpkg@v1
    - uses: julia-actions/julia-runtest@v1
