on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.8
          cache: 'poetry'
      - name: Install deploy key for BattModels/smirk
        uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387 #v0.9.0
        with:
          ssh-private-key: ${{ secrets.SMIRK_PRIVATE_KEY }}
      - run: poetry install
      - run: poetry show
      - run: source activate && pytest
